dashboard/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('schedule/view/week', views.MainView.as_view(), name='schedule_view_weekly'),
    path('meeting/<int:pk>/', views.MeetingDetailView.as_view(), name='meeting_detail'),
    path('meeting/edit/<int:pk>/', views.MeetingEditView.as_view(), name='meeting_edit'),
    path('meeting/comment/delete/', views.Comments.delete, name='comment_delete'),
    path('meeting/comment/modify/', views.Comments.modify, name='comment_modify'),
]

dashboard/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django_summernote import models as summer_model
from django_summernote import fields as summer_fields


class User(AbstractUser):
    nickname = models.CharField(max_length=20, blank=True)


class Meeting(summer_model.Attachment):
    proponent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='proponent')  # 제안자
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=False, related_name='participants')  # 참가자
    meet_date = models.DateTimeField(blank=False)
    meet_title = models.CharField(max_length=200, blank=True)
    meet_desc = models.CharField(max_length=500)
    meet_contents = summer_fields.SummernoteTextField(default='')
    created_date = models.DateTimeField(default=timezone.now)
    progress = models.BooleanField(default=False)
    file1 = models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')  # 첨부파일
    file2 = models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')


class Comment(models.Model):
    meet_schedule = models.ForeignKey('Meeting', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

dashboard/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from flatpickr import DateTimePickerInput


class MeetingAddForm(forms.ModelForm):
    meet_date = forms.DateTimeField(widget=DateTimePickerInput(options={
        'dateFormat': 'Y-m-d H:i',
    }))
    meet_title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    meet_desc = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control',
                                                                    'style': 'height: 100px; min-height: 100px;'
                                                                             'max-height: 200px;'}))
    participants = forms.CharField(widget=forms.SelectMultiple(attrs={'class': 'form-control choices'}), required=False)
    meet_contents = summer_fields.SummernoteTextFormField(label='', widget=forms.TextInput(), required=False, error_messages={'required': (u'내용을 입력해주세요'), })
    progress = forms.BooleanField(widget=forms.CheckboxInput(attrs={'id':'progress', 'class':'d-none'}), required=False)
    file1 = forms.FileField(label='첨부파일1', widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))
    file2 = forms.FileField(label='첨부파일2', widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Meeting
        fields = ('meet_date', 'meet_title', 'meet_desc', 'participants', 'meet_contents', 'progress', 'file1', 'file2')

    def __init__(self, *args, **kwargs):
        super(MeetingAddForm, self).__init__(*args, **kwargs)
        self.fields['file1'].required = False
        self.fields['file2'].required = False


class CommentForm(forms.ModelForm):
    text = forms.CharField(label='내용', widget=forms.Textarea(
        attrs={'class': 'form-control comment-input', 'placeholder': '내용', 'aria-label': '내용'}
    ), required=True)

    class Meta:
        model = Comment
        fields = ('text',)


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(label='계정명',widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter username'}
    ))
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter password'}
    ))


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

    username = forms.CharField(label='계정명', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter username'}
    ))
    password1 = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter password'}
    ))
    password2 = forms.CharField(label='비밀번호 재입력', widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter password again'}
    ))
    email = forms.EmailField(label='이메일', required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter email address'}
    ))
    nickname = forms.CharField(label='별명', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg', 'placeholder': 'Enter display nickname'}
    ))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email', 'nickname')

dashboard/views.py
import json
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from .forms import MeetingAddForm, RegisterForm, CommentForm
from .models import Meeting, Comment
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
import datetime

User = get_user_model()


class MainView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        form = MeetingAddForm

        return render(request, 'main.html', {
            'form': form,
            'participants': Participants.get_all_participants(),
            'schedule': MeetingSchedule.get_weekly_schedule(request),
            'schedule_all': MeetingSchedule.get_all_schedule(),
            'all_date': MeetingSchedule.get_after_7_days(),
            'comments_all': Comments.get_all_comments(),
        })

    @staticmethod
    @login_required
    def post(request):
        form = MeetingAddForm(request.POST)

        if form.is_valid():
            participants = request.POST.getlist('participants')
            all_user = User.objects.values_list('id', 'nickname')

            meet_schedule = form.save(commit=False)
            meet_schedule.proponent = request.user
            meet_schedule.save()

            for x in participants:
                participant_id = all_user.filter(nickname=x).values_list('id', flat=True)
                for y in participant_id:
                    meet_schedule.participants.add(y)

        return redirect('main')


class RegisterView(View):
    @staticmethod
    def get(request):
        form = RegisterForm

        return render(request, 'registration/register.html', {'form': form})

    @staticmethod
    def post(request):
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('main')
        else:
            form = RegisterForm(form.errors)
            return render(request, 'registration/register.html', {'form': form})


class MeetingDetailView(View):
    @staticmethod
    def get(request, pk):
        return render(request, 'meeting_detail.html', {
            'meeting': get_object_or_404(Meeting, pk=pk),
            'comment': CommentForm(),
            'contents': Meeting.objects.get(attachment_ptr_id=pk),
            'participants': Participants.get_current_participants(pk),
        })

    @staticmethod
    def post(request, pk):
        meeting = get_object_or_404(Meeting, pk=pk)
        comment = CommentForm(request.POST)

        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.meet_schedule = meeting
            comment.author = request.user
            comment.save()
            return redirect('meeting_detail', pk=meeting.pk)


class MeetingEditView(View):
    @staticmethod
    def get(request, pk):
        meeting = get_object_or_404(Meeting, pk=pk)
        form = MeetingAddForm(instance=meeting)
        participants = Participants.get_all_participants()
        current_participants = Participants.get_current_participants(pk)
        print(current_participants)
        return render(request, 'meeting_edit.html', {'meeting': meeting, 'form': form,
                                                     'participants': participants,
                                                     'current_participants': current_participants})

    @staticmethod
    @login_required
    def post(request, pk):
        meeting = get_object_or_404(Meeting, pk=pk)
        form = MeetingAddForm(request.POST, request.FILES, instance=meeting)
        participants = Participants.get_all_participants()
        current_participants = Participants.get_current_participants(pk)
        files = request.FILES.getlist('file_field')

        if form.is_valid():
            participants = request.POST.getlist('participants')
            all_user = User.objects.values_list('id', 'nickname')

            meet_schedule = form.save(commit=False)
            meet_schedule.proponent = request.user
            for file in files:
                a = getattr(meet_schedule, file)
                os.system('chmod 777 {}'.format(a.path))
            meet_schedule.save()

            meet_schedule.participants.remove(*meet_schedule.participants.all())

            for x in participants:
                participant_id = all_user.filter(nickname=x).values_list('id', flat=True)
                for y in participant_id:
                    meet_schedule.participants.add(y)
            return redirect('main')

        return render(request, 'meeting_edit.html', {'meeting': meeting, 'form': form,
                                                     'participants': participants,
                                                     'current_participants': current_participants})


class Participants:
    @staticmethod
    def get_all_participants():
        participants_json = []

        for val in User.objects.values_list('nickname', flat=True):
            participants_json.append({'value': val})

        return participants_json

    @staticmethod
    def get_current_participants(pk):
        user = User.objects
        participants_data = Meeting.objects.filter(id=pk).values_list('participants')
        participants_json = []

        for val in user.values_list('id', 'nickname'):
            if participants_data.filter(participants=val).exists():
                nickname = user.filter(id=val[0]).values_list('nickname', flat=True)[0]
                participants_json.append({'value': nickname, 'selected': 1})
            else:
                participants_json.append({'value': val[1], 'selected': 0})

        return participants_json


class MeetingSchedule:
    @staticmethod
    def get_after_7_days():
        date_array = []
        date_now = datetime.datetime.now()

        for current_days in range(0, 7):
            current_date = date_now + datetime.timedelta(days=current_days)
            date_array.append(current_date)

        return date_array

    @staticmethod
    def get_weekly_schedule(request):
        schedule_json = {}
        date_now = datetime.datetime.now()

        for current_days in range(0, 7):
            current_date = date_now + datetime.timedelta(days=current_days)

            schedule_data = Meeting.objects.filter(
                meet_date__contains=datetime.date(current_date.year, current_date.month, current_date.day)
            )

            for data in schedule_data:
                date_over = '1' if date_now >= data.meet_date else '0'
                joined = '1' if data.participants.filter(id=request.user.id) else '0'
                progress = '1' if data.progress else '0'

                schedule_json[data.id] = ({
                    'id': data.id, 'time': data.meet_date.strftime('%p %H:%M'),
                    'date': current_date.strftime('%Y-%m-%d'),
                    'title': data.meet_title, 'time_expired': date_over,
                    'joined': joined, 'schedule_ended': progress,
                })

        return schedule_json

    @staticmethod
    def get_all_schedule():
        schedule = Meeting.objects.all().order_by('-meet_date')[:12]
        return schedule


class Comments:
    @staticmethod
    def get_all_comments():
        comments = Comment.objects.all().order_by('-id')[:6]
        return comments

    @staticmethod
    def delete(request):
        if request.method == "POST":
            comment_id = json.loads(request.body)['pk']
            comment = get_object_or_404(Comment, pk=comment_id)

            if comment.author.pk == request.user.pk:
                comment.delete()
                message = 'removed'
            else:
                message = 'fail'
        context = {'success': message}
        return HttpResponse(json.dumps(context, ensure_ascii=False), content_type='application/json')

    @staticmethod
    def modify(request):
        if request.method == "POST":
            json_data = json.loads(request.body)
            comment = get_object_or_404(Comment, pk=json_data['pk'])
            
            if comment.author.pk == request.user.pk:
                comment.text = json_data['text']
                comment.save()
                message = 'modify'
            else:
                message = 'fail'
            context = {'success': message}
            return HttpResponse(json.dumps(context, ensure_ascii=False), content_type='application/json')

dashboard/templates/main.html
{% extends 'base.html' %}

{% block head %}
    <title>Meet Scheduler</title>
{% endblock head %}

{% block title %}Meet Scheduler{% endblock title %}

{% block content %}
    <div class="row no-gutters">
        <div class="col-7 col-md-8 col-lg-10 align-self-center">
            <h2 class="app-title no-margin"><i class="fa fa-calendar-week mr-3"></i>주간 일정</h2>
        </div>
        <div class="col-5 col-md-4 col-lg-2">
            <button id="btn-add-schedule" class="app-btn app-btn-lg bg-color-gray w-100" type="button">
                <i class="fa fa-plus mr-2"></i>일정 추가
            </button>
        </div>
    </div>
    {% include "schedule_view_weekly.html" %}

    <div class="row no-gutters">
        <div class="col-12 col-md-6">
            <div class="row">
                <div class="col-12">
                    <h2 class="app-title"><i class="fa fa-list mr-3"></i>전체 회의</h2>
                </div>
                <div class="col-12">
                    {% include "schedule_view_list_all.html" %}
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="row">
                <div class="col-12">
                    <h2 class="app-title"><i class="fa fa-comments mr-3"></i>최근 댓글</h2>
                </div>
                <div class="col-12">
                    {% include "recent_comments_all.html" %}
                </div>
            </div>
        </div>
    </div>

    <!-- Modal content -->
    <div id="modal-add-schedule" class="d-none">
        <form id="form-add-schedule" method="post">
            {% csrf_token %}
            {{ form.media }}
            <div class="row my-2">
                <div class="col-3 app-form-label align-self-center"><i class="fa fa-calendar-day mr-2"></i>회의 일자</div>
                <div class="col-9">{{ form.meet_date }}</div>
            </div>
            <div class="row my-2">
                <div class="col-3 app-form-label align-self-center"><i class="fa fa-comment mr-2"></i>회의 제목</div>
                <div class="col-9">{{ form.meet_title }}</div>
            </div>
            <div class="row my-2">
                <div class="col-3 app-form-label align-self-center"><i class="fa fa-users mr-2"></i>참가자</div>
                <div class="col-9">{{ form.participants }}</div>
            </div>
            <div class="row my-2">
                <div class="col-3 app-form-label align-self-center"><i class="fa fa-bookmark mr-2"></i>주제</div>
                <div class="col-9">{{ form.meet_desc }}</div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        const modal = new tingle.modal({
            footer: true,
            stickyFooter: true,
            closeMethods: ['button', 'escape'],
            closeLabel: "Close",
            cssClass: ['custom-class-1', 'custom-class-2'],
        });

        modal.setContent(document.querySelector('#modal-add-schedule').innerHTML);
        modal.addFooterBtn('취소', 'tingle-btn tingle-btn--danger', function() {
            modal.close();
        });
        modal.addFooterBtn('일정 추가', 'tingle-btn tingle-btn--primary', function() {
            const form = document.getElementById('form-add-schedule');
            form.submit();
            //modal.close();
        });

        document.getElementById('btn-add-schedule').onclick = function() {
            modal.open();
        };
    </script>
    <script type="text/javascript">
        const participantsForm = document.querySelector('#id_participants');
        const multipleChoices = new Choices(participantsForm, {
            choices: {{participants|safe}},
            duplicateItemsAllowed: false,
            searchEnabled: true,
            searchChoices: true,
            removeItems: true,
            removeItemButton: true,
            noResultsText: '가입된 사용자가 없습니다.',
            noChoicesText: '사용자를 선택해주세요.',
            itemSelectText: '클릭하여 선택',
        });
    </script>
{% endblock script %}

dashboard/templates/meeting_edit.html
{% extends 'base.html' %}

{% block head %}
    <title>Meet Scheduler</title>
{% endblock head %}

{% block title %}Meet Scheduler{% endblock title %}

{% block content %}
    <div class="app-schedule-body">
        <div class="meeting-form">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                <div class="row my-2">
                    <div class="col-3 app-form-label align-self-center"><i class="fa fa-calendar-day mr-2"></i>회의 일자
                    </div>
                    <div class="col-5">{{ form.meet_date }}</div>
                    <div id="btn-done" data-active="false" class="toolbar-item col-4 text-right">
                        회의록 작성완료<i class="fa fa-circle ml-2"></i>{{ form.progress }}
                    </div>
                </div>
                <div class="row my-2">
                    <div class="col-3 app-form-label align-self-center"><i class="fa fa-comment mr-2"></i>회의 제목</div>
                    <div class="col-9">{{ form.meet_title }}</div>
                </div>
                <div class="row my-2">
                    <div class="col-3 app-form-label align-self-center"><i class="fa fa-users mr-2"></i>참가자</div>
                    <div class="col-9">{{ form.participants }}</div>
                </div>
                <div class="row my-2">
                    <div class="col-3 app-form-label align-self-center"><i class="fa fa-bookmark mr-2"></i>주제</div>
                    <div class="col-9">{{ form.meet_desc }}</div>
                </div>
                <div class="row my-2">
                    <div class="col-3 app-form-label align-self-center"><i class="fa fa-list mr-2"></i>회의 내용</div>
                    <div class="col-9">{{ form.meet_contents }}</div>
                </div>
                <div class="form-group row">
                    <label for="exampleFormControlFile1" class="col-sm-1 col-form-label">첨부파일</label>
                    <div class="col-sm-10">
                        {{ form.file1 }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleFormControlFile1" class="col-sm-1 col-form-label">첨부파일</label>
                    <div class="col-sm-10">
                        {{ form.file2 }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-right">
                        <button onclick="location.href='{% url 'meeting_detail' pk=meeting.id %}'" type="button"
                                class="app-btn app-btn-lg bg-color-gray mr-2">취소
                        </button>
                        <button type="submit" class="app-btn app-btn-lg">변경내용 저장</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        const participantsForm = document.querySelector('#id_participants');
        const multipleChoices = new Choices(participantsForm, {
            choices: {{ current_participants|safe }},
            duplicateItemsAllowed: false,
            searchEnabled: true,
            searchChoices: true,
            removeItems: true,
            removeItemButton: true,
            noResultsText: '가입된 사용자가 없습니다.',
            noChoicesText: '사용자를 선택해주세요.',
            itemSelectText: '클릭하여 선택',
        });

        if (document.getElementById('progress').checked === true) {
            document.getElementById('btn-done').classList.add('active');
            document.getElementById('btn-done').setAttribute('data-active', 'true');
            document.getElementById('btn-done').children[0].classList.remove('fa-circle');
            document.getElementById('btn-done').children[0].classList.add('fa-check-circle');
        }

        document.getElementById('btn-done').onclick = function () {
            if (this.getAttribute('data-active') === 'true') {
                this.classList.remove('active');
                this.setAttribute('data-active', 'false');
                this.children[0].classList.add('fa-circle');
                this.children[0].classList.remove('fa-check-circle');
                this.children[1].checked = false;
                console.log(this.children[1].checked);
            } else {
                this.classList.add('active');
                this.setAttribute('data-active', 'true');
                this.children[0].classList.remove('fa-circle');
                this.children[0].classList.add('fa-check-circle');
                this.children[1].checked = true;
                console.log(this.children[1].checked);
            }
        };
    </script>
{% endblock %}

dashboard/templates/recent_comments_all.html
{% block content %}
    <div class="app-comment-body">
    {% for comment in comments_all %}
        <div class="app-comment-item">
            <div>
                <strong class="mr-2"><i class="fa fa-user-circle mr-2"></i>{{ comment.author }}
                </strong><span class="comment-meta">{{ comment.created_date }} (<a href="{% url 'meeting_detail' pk=comment.meet_schedule.id %}">{{ comment.meet_schedule.meet_title|truncatechars:20 }}</a>에서)</span>
            </div>
            <div class="comment-text">{{ comment.text }}</div>
        </div>
    {% endfor %}
    </div>
{% endblock content %}

{% block script %}
{% endblock script %}

dashboard/templates/schedule_view_list_all.html
{% block content %}
    <div class="app-list-body">
        <table class="table table-bordered table-striped color-gray font-sm">
            <thead class="thead-dark">
                <tr>
                    <th>일자</th>
                    <th>제목</th>
                    <th>완료</th>
                </tr>
            </thead>
            <tbody>
                {% for schedule in schedule_all %}
                <tr class="schedule-item" data-id="{{ schedule.id }}">
                    <td>{{ schedule.meet_date|date:"Y-m-d l H:i" }}</td>
                    <td class="font-weight-bold">{{ schedule.meet_title }}</td>
                    <td class="text-center color-green">{% if schedule.progress %}<i class="fa fa-check-circle"></i>{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        const scheduleItem = document.querySelectorAll('.app-list-body .schedule-item');

        if (scheduleItem != null) {
            Array.from(scheduleItem).forEach(function (el) {
                el.onclick = function () {
                    location.href = '{% url 'meeting_detail' pk=123 %}'.replace('123', this.getAttribute('data-id'));
                }
            });
        }
    </script>
{% endblock script %}

dashboard/templates/schedule_view_weekly.html
{% block content %}
    <div class="app-weekly-feed">
        <div class="app-weekly-toolbar row no-gutters">
            <div class="col-9 color-gray">
                <span id="schedule-count" class="font-weight-bold"></span> 개의 주간 회의
            </div>
            <div id="btn-only-me" data-active="false" class="toolbar-item col-3 text-right">
                내가 포함된 일정만 보기<i class="fa fa-circle ml-2"></i>
            </div>
        </div>
        <div class="app-weekly-body">
            {% for current_date in all_date %}
                <div class="date-row">
                    <div id="date-{{ current_date|date:"Y-m-d" }}" class="day">{{ current_date|date:"m/d l" }}</div>
                    <div id="schedule-{{ current_date|date:"Y-m-d" }}" class="schedule"></div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        const jsonData = {{ schedule|safe }};
        let scheduleCount = 0;
        let ended, expired, joined = "";

        for (let key in jsonData) {
            let data = jsonData[key];
            let url = "{% url 'meeting_detail' pk=123 %}".replace('123', data.id);
            ended = "";
            expired = "";
            joined = "";

            if (data.time_expired === "1") expired = "time-ended";
            if (data.joined === "1") joined = "<i class='fa fa-star mr-1 color-yellow'></i>";
            if (data.schedule_ended === "1") ended = "<i class='fa fa-check-circle mr-1 color-green'></i>";

            let htmlData =
                "<div data-joined='"+data.joined+"' onclick='location.href=\"" + url + "\"' " +
                "class='schedule-item " + expired + "'>" + joined + ended +
                    "<span class='time'>" + data.time + "</span>" +
                    stringLimit(data.title, 40) +
                "</div>";
            document.getElementById('schedule-' + data.date).innerHTML += htmlData;
            scheduleCount++;
        }

        document.getElementById('schedule-count').innerHTML = scheduleCount.toString();

        document.getElementById('btn-only-me').onclick = function() {
            showAllSchedule();

            if (this.getAttribute('data-active') === 'true') {
                this.classList.remove('active');
                this.setAttribute('data-active', 'false');
                this.children[0].classList.add('fa-circle');
                this.children[0].classList.remove('fa-check-circle');
            } else {
                this.classList.add('active');
                this.setAttribute('data-active', 'true');
                this.children[0].classList.remove('fa-circle');
                this.children[0].classList.add('fa-check-circle');
                filterSchedule();
            }
        };

        function filterSchedule() {
            const schedule = document.getElementsByClassName('schedule-item');

            for (let i=0; i<schedule.length; i++) {
                if (schedule[i].getAttribute('data-joined') === '0')
                    schedule[i].classList.add('d-none');
            }
        }

        function showAllSchedule() {
            const schedule = document.getElementsByClassName('schedule-item');

            for (let i=0; i<schedule.length; i++) {
                schedule[i].classList.remove('d-none');
            }
        }
    </script>
{% endblock script %}